import {inspectText,sample,MAX_BYTES} from './inspect.mjs';
const $=id=>document.getElementById(id), input=$('workflow-text'), file=$('workflow-file');
let current=null, revision=0;
const labels={OUT_OF_SCOPE:'Fora do recorte: há dependências que esta extração não cobre.',REVIEW_REQUIRED:'Revisão necessária: parâmetros ou estrutura não estão no recorte.',STRUCTURAL_CANDIDATE:'Candidata estrutural: ainda precisa de comparação de comportamento.'};
const reasons={NODE_COUNT:'O recorte exige de um a oito nós.',UNRECOGNIZED_FIELDS:'Há campos não reconhecidos; não foram interpretados silenciosamente.',ACTIVE_WORKFLOW:'Workflow declarado ativo: transição operacional precisa de revisão.',INVALID_ACTIVE_FLAG:'Flag de ativação não é booleana.',PERSISTED_OR_PINNED_DATA:'Estado persistido ou dados fixados exigem tratamento separado.',WORKFLOW_SETTINGS:'Configurações de workflow podem mudar execução e falhas.',STRUCTURE_LIMIT:'Estrutura excede profundidade/quantidade permitida.',DYNAMIC_EXPRESSION:'Expressão dinâmica ou referência a contexto encontrada.',POSSIBLE_SECRET:'Texto compatível com possível segredo: revisar o export.',CREDENTIAL_OR_SECRET_FIELD:'Campo de credencial/segredo presente.',UNSAFE_KEY:'Campo de objeto reservado não permitido.',INVALID_NODE:'Nó inválido.',INVALID_OR_DUPLICATE_NODE_NAME:'Nome vazio/duplicado impede associar conexões.',MISSING_OR_DUPLICATE_NODE_ID:'Identificador ausente/duplicado exige revisão.',EXECUTABLE_CODE:'Código executável está fora do recorte.',UNSUPPORTED_NODE:'Tipo de nó não reconhecido neste recorte.',UNREVIEWED_NODE_VERSION:'Versão de nó não revisada.',DISABLED_OR_INVALID_NODE_FLAG:'Nó desabilitado ou flag inválida.',RUNTIME_NODE_BEHAVIOR:'Retentativa, tolerância a erro ou comportamento de runtime definido.',INVALID_PARAMETERS:'Parâmetros do nó não são um objeto.',UNRECOGNIZED_PARAMETERS:'Parâmetros adicionais precisam de revisão.',NON_GET_REQUEST:'Método HTTP fora do recorte GET.',AUTHENTICATED_REQUEST:'Requisição depende de autenticação.',HTTP_OPTIONS:'Opções HTTP exigem comparação separada.',HTTP_EXTRA_PAYLOAD:'Headers/query/body não são cobertos.',URL_REQUIRES_REVIEW:'URL fora do recorte HTTPS sem porta/query/fragmento/identidade.',INVALID_URL:'URL ausente ou inválida.',NON_LITERAL_SET_MODE:'Set fora do modo literal.',SET_OPTIONS:'Opções Set não cobertas.',INVALID_SET_RETENTION:'Retenção de campos inválida.',INVALID_ASSIGNMENTS:'Lista de atribuições ausente ou fora do limite.',INVALID_ASSIGNMENT:'Atribuição inválida.',INVALID_OR_DUPLICATE_ASSIGNMENT_NAME:'Nome de campo inválido ou duplicado.',NON_LITERAL_ASSIGNMENT:'Valor/tipo da atribuição não é literal suportado.',INVALID_CONNECTION_SOURCE:'Origem de conexão não pode ser associada.',NON_MAIN_CONNECTION:'Canal de conexão diferente de main.',INVALID_CONNECTION_PORT:'Porta de conexão inválida.',MULTIPLE_OUTPUT_PORTS:'Múltiplas saídas não cobertas.',INVALID_CONNECTION_TARGET:'Destino/porta de conexão inválido.',BRANCH_OR_MERGE:'Ramificação ou junção exige semântica de itens separada.',MANUAL_START_REQUIRED:'É necessário exatamente um início manual sem entrada.',CYCLE:'Ciclo encontrado.',DISCONNECTED_NODES:'Há nós que não pertencem à cadeia de início.'};
function invalidate(){revision++;current=null;$('input-message').textContent='';$('report-content').replaceChildren();$('assessment-status').textContent='Entrada alterada. Analise novamente.';$('assessment-status').removeAttribute('data-status');$('download-json').disabled=$('download-plan').disabled=true;}
input.addEventListener('input',invalidate);
function text(tag,content,parent){const e=document.createElement(tag);e.textContent=content;parent.append(e);return e;}
function list(title,items,parent){text('h3',title,parent);const ul=document.createElement('ul');items.forEach(v=>text('li',v,ul));parent.append(ul);}
function show(r){const panel=$('report-content');panel.replaceChildren();$('assessment-status').textContent=labels[r.status];$('assessment-status').dataset.status=r.status;
 const flow=document.createElement('ul');flow.className='node-list';r.nodes.forEach(n=>text('li',`${n.node} · ${n.kind} · v${n.version??'?'}`,flow));panel.append(flow);
 text('p',`Cadeia detectada: ${r.linear_order.join(' → ')||'não associável'}`,panel);
 list('Pontos que impedem ou exigem revisão',r.findings.length?r.findings.map(f=>`${f.node?f.node+' · ':''}${reasons[f.code]||f.code} [${f.code}]`):['Nenhum alerta estrutural reconhecido. Isso não aprova uma migração.'],panel);
 list('O que não sai junto com a lógica',r.losses,panel);list('Plano antes de converter',r.next_checks,panel);text('p','SHA-256 do texto analisado (UTF-8) · '+r.input_sha256,panel).className='hash';list('Limites da análise',r.limitations,panel);
 $('download-json').disabled=$('download-plan').disabled=false;
}
$('assess').addEventListener('click',async()=>{invalidate();const generation=revision,raw=input.value;try{const r=inspectText(raw),bytes=new TextEncoder().encode(raw);const digest=await crypto.subtle.digest('SHA-256',bytes);if(generation!==revision)return;r.input_sha256=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,'0')).join('');r.input_bytes=bytes.length;r.hash_scope='analyzed_text_utf8';r.limitations.push('O hash cobre o texto UTF-8 analisado; BOM e quebras de linha podem diferir dos bytes originais do arquivo.');current=r;show(r);$('input-message').textContent='Inspeção local concluída. Nenhuma chamada do workflow foi feita.';}catch(e){if(generation!==revision)return;$('assessment-status').textContent=e.message;$('input-message').textContent='Entrada recusada; relatório anterior removido.';}});
$('sample').addEventListener('click',()=>{input.value=JSON.stringify(sample,null,2);file.value='';invalidate();$('input-message').textContent='Exemplo fictício com início manual e Set literal. Clique em analisar.';});
$('clear').addEventListener('click',()=>{input.value='';file.value='';invalidate();$('input-message').textContent='Conteúdo desta ferramenta removido da memória da aba.';});
file.addEventListener('change',async()=>{invalidate();input.value='';const generation=revision,f=file.files[0];if(!f)return;if(f.size>MAX_BYTES){$('input-message').textContent='Arquivo excede 1 MiB; não foi lido.';return;}try{const raw=await f.text();if(generation!==revision)return;input.value=raw;$('input-message').textContent='Arquivo aberto localmente. Clique em analisar.';}catch{if(generation===revision)$('input-message').textContent='Não foi possível ler o arquivo.';}});
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download-json').addEventListener('click',()=>{if(current)download('exitforge-analysis.json',JSON.stringify(current,null,2),'application/json');});
$('download-plan').addEventListener('click',()=>{if(!current)return;const r=current;download('exitforge-review.txt',`EXITFORGE — TRIAGEM LOCAL\n${labels[r.status]}\nTexto analisado UTF-8 SHA-256: ${r.input_sha256}\n\nALERTAS\n${r.findings.map(f=>`${f.node||'Fluxo'}: ${reasons[f.code]||f.code}`).join('\n')||'Nenhum alerta estrutural reconhecido.'}\n\nPERDAS\n${r.losses.join('\n')}\n\nPLANO DE CONFRONTO\n${r.next_checks.join('\n')}\n\nLIMITES\n${r.limitations.join('\n')}\n\nNenhuma migração, chamada HTTP, compra ou validação comercial realizada.\n`,'text/plain;charset=utf-8');});
