import {prepareExtraction,runOffline,pythonSource} from './extract.mjs';
import {sample} from './inspect.mjs';
const $=id=>document.getElementById(id);let plan=null,result=null;
function invalidate(){plan=null;result=null;$('extract-output').textContent='';$('extract-plan').textContent='';$('extract-python').disabled=$('extract-plan-download').disabled=$('extract-result-download').disabled=true;$('extract-confirm').checked=false;$('extract-status').textContent='Prepare novamente após alterar o workflow.';}
$('workflow-text').addEventListener('input',invalidate);$('workflow-file').addEventListener('change',invalidate);
for(const id of ['sample','clear'])$(id).addEventListener('click',invalidate);
$('extraction-sample').addEventListener('click',()=>{const w=structuredClone(sample);w.nodes[1].parameters.includeOtherFields=true;$('workflow-text').value=JSON.stringify(w,null,2);$('workflow-text').dispatchEvent(new Event('input'));$('item-input').value='[{"order_id":"EXAMPLE-1","quantity":2}]';$('extract-status').textContent='Exemplo fictício: Set literal com retenção explicitamente true. Prepare a transformação.';});
$('prepare-extraction').addEventListener('click',()=>{invalidate();try{plan=prepareExtraction($('workflow-text').value);$('extract-plan').textContent=plan.steps.map(s=>`${s.node} · ${s.retain_input?'conserva campos de entrada':'descarta campos não definidos'}\n${s.fields.map(f=>`${f.name} (${f.type}): ${JSON.stringify(f.value)}`).join('\n')}`).join('\n\n');$('extract-status').textContent='Transformação offline preparada. Valores são locais; equivalência n8n não foi conferida.';$('extract-plan-download').disabled=false;}catch(e){$('extract-status').textContent='Extração recusada: '+e.message;}});
$('item-input').addEventListener('input',()=>{result=null;$('extract-output').textContent='';$('extract-result-download').disabled=true;});
$('run-extraction').addEventListener('click',()=>{result=null;$('extract-output').textContent='';$('extract-result-download').disabled=true;if(!plan){$('extract-status').textContent='Prepare uma transformação elegível primeiro.';return;}try{result=runOffline(plan,$('item-input').value);$('extract-output').textContent=JSON.stringify(result.items,null,2);$('extract-status').textContent=`Transformação local concluída: ${result.items.length} objetos. Zero chamadas de rede; confronto n8n não realizado.`;$('extract-result-download').disabled=false;}catch(e){$('extract-status').textContent='Entrada/saída recusada: '+e.message;}});
$('extract-confirm').addEventListener('change',()=>{$('extract-python').disabled=!(plan&&$('extract-confirm').checked);});
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('extract-python').addEventListener('click',()=>{if(plan&&$('extract-confirm').checked)download('extracted.py',pythonSource(plan),'text/x-python;charset=utf-8');});
$('extract-plan-download').addEventListener('click',()=>{if(plan)download('exitforge-offline-plan.json',JSON.stringify(plan,null,2),'application/json');});
$('extract-result-download').addEventListener('click',()=>{if(result)download('exitforge-offline-result.json',JSON.stringify(result,null,2),'application/json');});
