import assert from 'node:assert/strict';
import {test} from 'node:test';
import {spawnSync} from 'node:child_process';
import {sample,MAX_BYTES} from './inspect.mjs';
import {prepareExtraction,parseExtractionJSON,runOffline,pythonSource} from './extract.mjs';
const workflow=(retain=true)=>{const w=structuredClone(sample);w.nodes[1].parameters.includeOtherFields=retain;return w;};
const plan=w=>prepareExtraction(JSON.stringify(w));
function python(p,input){return spawnSync('python3',['-c',pythonSource(p)],{input,encoding:'utf8',maxBuffer:2*MAX_BYTES});}
test('explicit retention produces runnable original Python with same plain item output',()=>{const p=plan(workflow()),raw='[{"order_id":"000123","quantity":2}]';const expected=runOffline(p,raw);const got=python(p,raw);assert.equal(got.status,0,got.stderr);assert.deepEqual(JSON.parse(got.stdout),expected.items);assert.equal(p.n8n_equivalence_verified,false);assert.equal(p.network_enabled,false);assert.equal(p.production_approved,false);});
test('discard policy is explicit and survives Python generation',()=>{const p=plan(workflow(false)),raw='[{"untouched":1},{}]';assert.deepEqual(runOffline(p,raw).items.map(Object.keys),[['report_type'],['report_type']]);assert.deepEqual(JSON.parse(python(p,raw).stdout),JSON.parse(JSON.stringify(runOffline(p,raw).items)));});
test('missing retention and version defaults cannot be inferred',()=>{assert.throws(()=>plan(sample),/explícito/);const w=workflow();delete w.nodes[1].parameters.mode;assert.throws(()=>plan(w),/explícito/);w.nodes[1].typeVersion=3.3;assert.throws(()=>plan(w),/v3.4/);});
test('HTTP and credentials remain excluded from generated code',()=>{const w=workflow();w.nodes[1].type='n8n-nodes-base.httpRequest';w.nodes[1].typeVersion=4.2;w.nodes[1].parameters={url:'https://example.com',method:'GET',options:{}};assert.throws(()=>plan(w),/HTTP/);const c=workflow();c.nodes[1].credentials={api:{name:'synthetic'}};assert.throws(()=>plan(c),/bloqueada/);});
test('literal strings cannot inject Python through quotes, newlines or backslashes',()=>{const w=workflow();w.nodes[1].parameters.assignments.assignments[0].value='quote"\\\n__import__("os").system("echo INJECTION") 🧪 </script>';const p=plan(w),raw='[{}]';const got=python(p,raw);assert.equal(got.status,0,got.stderr);assert.deepEqual(JSON.parse(got.stdout),JSON.parse(JSON.stringify(runOffline(p,raw).items)));assert.equal(got.stderr,'');});
test('field numeric/boolean types are retained without implicit conversion',()=>{const w=workflow();w.nodes[1].parameters.assignments.assignments.push({id:'b',name:'count',type:'number',value:9007199254740991},{id:'c',name:'enabled',type:'boolean',value:false});const p=plan(w),raw='[{"count":1}]';assert.deepEqual(JSON.parse(python(p,raw).stdout),JSON.parse(JSON.stringify(runOffline(p,raw).items)));});
test('decimal/exponent/unsafe input quantities refused equally with no stdout',()=>{const p=plan(workflow());for(const raw of ['[{"x":1.2}]','[{"x":1e2}]','[{"x":9007199254740992}]','[{"x":NaN}]']){assert.throws(()=>runOffline(p,raw));const got=python(p,raw);assert.equal(got.status,2);assert.equal(got.stdout,'');}});
test('decimal assignment and dot/prototype field names cannot generate a plan',()=>{for(const value of [1.2,9007199254740992]){const w=workflow();Object.assign(w.nodes[1].parameters.assignments.assignments[0],{type:'number',value});assert.throws(()=>plan(w));}for(const name of ['foo.bar','__proto__','constructor']){const w=workflow();w.nodes[1].parameters.assignments.assignments[0].name=name;assert.throws(()=>plan(w));}});
test('duplicate/reserved workflow JSON and input keys are refused',()=>{assert.throws(()=>parseExtractionJSON('{"nodes":[],"nodes":[],"connections":{}}'));const p=plan(workflow());for(const raw of ['[{"x":1,"x":2}]','[{"__proto__":1}]','[{"constructor":1}]']){assert.throws(()=>runOffline(p,raw));assert.equal(python(p,raw).stdout,'');assert.equal(python(p,raw).status,2);}});
test('n8n envelopes/empty list have explicit local behavior only',()=>{const p=plan(workflow());assert.deepEqual(runOffline(p,'[]').items,[]);assert.deepEqual(JSON.parse(python(p,'[]').stdout),[]);for(const raw of ['{}','[1]','[null]','[{"json":{}}]','[{"binary":{}}]','[{"pairedItem":0}]']){assert.throws(()=>runOffline(p,raw));assert.equal(python(p,raw).status,2);}});
test('1000 input objects accepted, 1001 refused in both processes',()=>{const p=plan(workflow());const a=JSON.stringify(Array.from({length:1000},()=>({})));assert.equal(runOffline(p,a).items.length,1000);assert.equal(JSON.parse(python(p,a).stdout).length,1000);const b=JSON.stringify(Array.from({length:1001},()=>({})));assert.throws(()=>runOffline(p,b));assert.equal(python(p,b).status,2);});
test('actual input byte limits match and malformed data produces no partial output',()=>{const p=plan(workflow());const valid='[{}]'.padEnd(MAX_BYTES,' ');assert.equal(python(p,valid).status,0);assert.equal(runOffline(p,valid).items.length,1);assert.throws(()=>runOffline(p,valid+' '));assert.equal(python(p,valid+' ').status,2);const malformed='[{"ok":1},';assert.throws(()=>runOffline(p,malformed));const got=python(p,malformed);assert.equal(got.status,2);assert.equal(got.stdout,'');});
test('output expansion is bounded per row before producing a result',()=>{const w=workflow();w.nodes[1].parameters.assignments.assignments[0].value='x'.repeat(8192);const p=plan(w),raw=JSON.stringify(Array.from({length:200},()=>({})));assert.throws(()=>runOffline(p,raw),/Saída/);const got=python(p,raw);assert.equal(got.status,2);assert.equal(got.stdout,'');});
test('input objects are not modified and ordered Set operations are honored',()=>{const w=workflow();w.nodes.push({...structuredClone(w.nodes[1]),id:'s3',name:'Final'});w.nodes[2].parameters.assignments.assignments[0].value='last';w.connections.Etiqueta={main:[[{node:'Final',type:'main',index:0}]]};const p=plan(w),raw='[{"report_type":"before"}]';assert.equal(runOffline(p,raw).items[0].report_type,'last');assert.equal(JSON.parse(python(p,raw).stdout)[0].report_type,'last');assert.equal(raw,'[{"report_type":"before"}]');});
test('unpaired Unicode and excessive nesting rejected before emitting output',()=>{const p=plan(workflow());for(const raw of ['[{"x":"\\ud800"}]','['+'{"x":'.repeat(22)+'null'+'}'.repeat(22)+']']){assert.throws(()=>runOffline(p,raw));const got=python(p,raw);assert.equal(got.status,2);assert.equal(got.stdout,'');}});

test('invalid Unicode cannot be discarded before validation by a nonretaining Set',()=>{const p=plan(workflow(false));for(const raw of ['[{"lost":"\\ud800"}]','[{"lost":"\\udc00"}]','[{"\\ud800":"lost"}]']){assert.throws(()=>runOffline(p,raw));const got=python(p,raw);assert.equal(got.status,2);assert.equal(got.stdout,'');}});
