import{parseStrict,reconcile,totals}from'./reconcile.mjs';
import{demoBundle}from'./examples.mjs';
import{eventTrail,trailLabels,createDossier,parseDossier,reportHtml}from'./dossier.mjs';
import{setupGuided}from'./guided-ui.mjs';
const $=id=>document.getElementById(id),names=['contract','events','invoice'];
let current=null,revision=0,inputPreparation=null,pendingDossier=null,trailPage=0,dossierOperation=0;
const descriptions={duplicate_event:'Evento idêntico repetido: contado uma vez. Confira a origem da duplicação.',conflicting_event_id:'Mesmo ID com conteúdos diferentes. Não é possível escolher qual evento é válido.',unknown_meter:'Evento usa medidor ausente no contrato.',unit_mismatch:'Unidade do evento difere da unidade contratada.',outside_period_excluded:'Evento fora de [início, fim): excluído da quantidade.',late_event_requires_review:'Evento recebido depois do corte. É necessário revisar a base antes de calcular.',invalid_refund_reference:'Estorno não referencia uso elegível anterior do mesmo medidor.',refund_exceeds_original:'Soma de estornos excede a quantidade do uso original.',unknown_invoice_meter:'Linha de fatura usa medidor ausente no contrato.',invoice_unit_mismatch:'Unidade da fatura difere da unidade contratada.',multiple_lines_per_meter_unsupported:'Mais de uma linha para o mesmo medidor. Este recorte não agrega múltiplas linhas.'};
const invalidMessages={'incomplete export; comparison forbidden':'Export declarado incompleto: comparação monetária recusada.','pilot period exceeds 31 days':'Este recorte aceita até 31 dias de período.','unsupported pricing or rounding':'Somente preço linear constante e arredondamento half-up por total de medidor.','invoice period mismatch':'O período da fatura não coincide exatamente com o contrato.','invalid calendar timestamp':'Data de calendário inexistente.','customer mismatch':'Os três arquivos não têm o mesmo ID de cliente.','mixed data classes':'Os três arquivos precisam declarar a mesma classe: SIMULATED ou USER_SUPPLIED.','currency mismatch/unsupported':'A moeda precisa coincidir e ser BRL, USD ou EUR.','decimal must be unsigned plain string, <=12 integer/6 fractional digits':'Valores decimais precisam ser textos sem sinal ou notação científica, com até 12 dígitos inteiros e 6 casas.','amount requires exactly two decimals':'Valor faturado precisa ter exatamente duas casas decimais como texto.','invalid period/cutoff':'Exige início < fim ≤ corte.','receipt before occurrence':'Recebimento de evento não pode preceder sua ocorrência.'};
const node=(tag,text,className)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;};
const money=(value,currency)=>{const negative=value.startsWith('-'),clean=value.replace(/^-/,'');const[a,b='00']=clean.split('.');return`${negative?'− ':''}${({BRL:'R$',USD:'US$',EUR:'€'})[currency]??currency} ${a.replace(/\B(?=(\d{3})+(?!\d))/g,'.')},${b.padEnd(2,'0')}`;};
function invalidate(){pendingDossier=null;$('dossier-confirmation').hidden=true;revision++;current=null;inputPreparation=null;$('result').hidden=true;$('input-error').hidden=true;$('class-label').textContent='Entradas alteradas; confira novamente';}
function reset(){invalidate();guide.reset();for(const name of names){$('input-'+name).value='';$('file-'+name).value='';}$('scenario-panel').hidden=true;$('class-label').textContent='Nenhuma entrada carregada';$('mode-note').textContent='Nenhum dado foi carregado. A demonstração usa somente eventos inventados; não representa economia ou resultado de cliente.';}
function showInputError(message){$('input-error').replaceChildren(node('strong','Não foi possível conferir. '),node('span',message));$('input-error').hidden=false;}
function render(report,c){
 const blocked=report.status==='blocked',simulated=report.data_class==='SIMULATED';$('result').hidden=false;
 $('result-title').textContent=blocked?'Base insuficiente para concluir valores':report.status==='matched'?'Valores compatíveis com a base informada':'Há diferenças ou avisos para revisar';
 $('result-description').textContent=blocked?'Nenhuma comparação monetária foi emitida. Corrija a entrada indicada e confira novamente.':simulated?'Demonstração fictícia. Os valores abaixo ilustram o cálculo; não são receita recuperada nem evidência de cliente.':'Resultado baseado nas entradas e declarações fornecidas. Completude e autenticidade não foram verificadas de forma independente.';
 $('result-status').textContent=blocked?'BLOQUEADO':report.status==='matched'?'COMPATÍVEL':'REVISAR';$('result-status').style.background=blocked?'#fff0ec':report.status==='matched'?'#e6f3ee':'#fff5e5';
 const context=$('context');context.replaceChildren(node('span',`Classe: ${report.data_class??'não validada'}`));
 if(c?.period_start&&c?.period_end)context.append(node('span',`Período UTC: ${c.period_start} → ${c.period_end} (fim excluído)`));if(c?.invoice_cutoff)context.append(node('span',`Corte UTC: ${c.invoice_cutoff}`));
 const metrics=$('metrics');metrics.replaceChildren();const sums=totals(report);
 if(sums){const cards=[['Esperado pelo contrato',sums.expected,'Uso líquido × preço por medidor'],['Informado na fatura',sums.billed,'Valores das linhas recebidas'],['Diferença assinada',sums.delta,'Esperado − faturado; revisar antes de agir']];for(const[label,amount,hint]of cards){const card=node('div',undefined,'metric');card.append(node('p',label),node('strong',money(amount,report.currency)),node('small',hint));metrics.append(card);}}
 const issues=$('issues');issues.replaceChildren();for(const[key,label]of[['errors','Por que a conferência foi bloqueada'],['warnings','Avisos sobre a base']]){if(!report[key].length)continue;const block=node('div',undefined,'issue-list'+(key==='errors'?' blocked':''));block.append(node('h3',label));const list=node('ul');for(const issue of report[key].slice(0,50)){const detail=issue.detail?(invalidMessages[issue.detail]??issue.detail):(descriptions[issue.code]??issue.code);list.append(node('li',`${detail}${issue.ref?` ID: ${issue.ref}.`:''} [${issue.code}]`));}if(report[key].length>50)list.append(node('li',`Mostrando os primeiros 50 de ${report[key].length} itens. O relatório JSON preserva todos.`));block.append(list);issues.append(block);}
 const comparison=$('comparison');comparison.replaceChildren();
 if(report.comparison.length){const wrap=node('div',undefined,'table-wrap'),table=node('table'),thead=node('thead'),head=node('tr');for(const h of['MEDIDOR / UNIDADE','PREÇO / UNIDADE','USO LÍQUIDO','QTDE. FATURADA','ESPERADO','FATURADO','DIFERENÇA / REVISÃO'])head.append(node('th',h));thead.append(head);table.append(thead);const tbody=node('tbody');
 for(const row of report.comparison){const tr=node('tr'),meter=node('td',row.meter_id);meter.append(node('span',row.unit,'meter-unit'));tr.append(meter,node('td',money(c.meters.find(m=>m.meter_id===row.meter_id)?.unit_price??'0',report.currency)),node('td',row.contractual_quantity),node('td',row.invoice_quantity),node('td',money(row.expected_amount,report.currency)),node('td',money(row.invoice_amount,report.currency)));const candidate=report.adjustment_candidates.find(x=>x.meter_id===row.meter_id),delta=node('td',money(row.signed_delta,report.currency),candidate?'review':'');if(candidate)delta.append(node('span',candidate.interpretation==='possible_underbilling'?'Possível valor menor na fatura. Confira uso, preço e corte.':candidate.interpretation==='possible_overbilling'?'Possível valor maior na fatura. Confira uso, preço e corte.':'Quantidade diverge, mesmo com valor igual.','row-detail'));else delta.append(node('span','Quantidade e valor coincidem.','row-detail'));tr.append(delta);tbody.append(tr);}table.append(tbody);wrap.append(table);comparison.append(wrap);}
 $('download-csv').disabled=blocked;trailPage=0;renderTrail(report);
}
function renderTrail(report){
 const target=$('event-trail');target.replaceChildren();const trail=report.event_trail;if(!trail)return;
 target.append(node('h3','Por que cada evento entrou — ou não entrou'),node('p',trail.notice,'note'));
 const meter=$('trail-meter'),selected=meter.value;meter.replaceChildren();const all=node('option','Todos os medidores');all.value='';meter.append(all);for(const id of [...new Set(trail.rows.map(r=>r.meter_id))]){const o=node('option',id);o.value=id;meter.append(o);}meter.value=selected;
 const query=$('trail-query').value.trim().toLowerCase(),rows=trail.rows.filter(r=>(!meter.value||r.meter_id===meter.value)&&(!query||r.event_id.toLowerCase().includes(query)||(r.reverses??'').toLowerCase().includes(query)));
 const max=Math.max(0,Math.ceil(rows.length/100)-1);trailPage=Math.min(trailPage,max);const visible=rows.slice(trailPage*100,(trailPage+1)*100);
 $('trail-count').textContent=rows.length?`${rows.length} linhas · página ${trailPage+1}/${max+1} · até 100 linhas por página`:'Nenhum evento para este filtro.';$('trail-prev').disabled=trailPage===0;$('trail-next').disabled=trailPage>=max;
 const wrap=node('div',undefined,'table-wrap'),table=node('table'),head=node('tr');for(const h of ['Linha / evento','Medidor / unidade','Uso ou estorno','Quantidade declarada','Situação / contribuição final','Ocorrência / recebimento UTC'])head.append(node('th',h));const thead=node('thead');thead.append(head);table.append(thead);const body=node('tbody');
 for(const r of visible){const tr=node('tr');for(const v of [`${r.input_row} / ${r.event_id}`,`${r.meter_id} / ${r.unit}`,`${r.kind}${r.reverses?' → '+r.reverses:''}`,r.declared_quantity,`${trailLabels[r.evaluation]??r.evaluation} · ${r.signed_quantity??'contribuição não emitida'}`,`${r.occurred_at} / ${r.received_at}`])tr.append(node('td',v));body.append(tr);}table.append(body);wrap.append(table);target.append(wrap);
}

async function run(){
 const version=++revision;current=null;$('result').hidden=true;$('input-error').hidden=true;const raw={},docs={};
 try{for(const name of names){raw[name]=$('input-'+name).value;try{docs[name]=parseStrict(raw[name]);}catch(error){throw new Error(`${name}.json: ${error.message}`);}}}catch(error){showInputError(error.message);return;}
 const report=reconcile(docs.contract,docs.events,docs.invoice);
 report.browser_adapter={version:'1',arithmetic:'BigInt decimal coefficients; meter-total half-up',period_limit_days:31,authenticity:'not_verified',completeness:'user_asserted',customer_acceptance:'not_observed'};
 report.report_version=2;report.event_trail=eventTrail(docs.contract,docs.events,report);
 if(inputPreparation)report.browser_adapter.input_preparation=inputPreparation;
 report.input_sha256={};
 try{for(const name of names){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw[name]));report.input_sha256[name+'.json']=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}}catch{report.hash_notice='SHA-256 unavailable in this browser; input authenticity not verified.';}
 if(version!==revision)return;current={report,contract:docs.contract,raw:structuredClone(raw)};$('class-label').textContent=report.data_class==='SIMULATED'?'DADOS FICTÍCIOS':report.data_class==='USER_SUPPLIED'?'DADOS FORNECIDOS':'CLASSE NÃO VALIDADA';render(report,docs.contract);
}
function download(filename,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=node('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const fields=['meter_id','unit','contractual_quantity','invoice_quantity','expected_amount','invoice_amount','signed_delta'];
function csv(report){const quote=v=>'"'+String(v).replaceAll('"','""')+'"';return fields.join(',')+'\n'+report.comparison.map(row=>fields.map(k=>quote(['meter_id','unit'].includes(k)&&/^[=+\-@]/.test(row[k])?"'"+row[k]:row[k])).join(',')).join('\n')+'\n';}

const guide=setupGuided({invalidate,download,applyBundle:(bundle,preparation,inputs)=>{invalidate();for(const name of names)$('input-'+name).value=inputs[name];inputPreparation=preparation;}});
$('class-label').textContent='Nenhuma entrada carregada';
$('load-demo').addEventListener('click',()=>{reset();$('scenario').value='difference';loadScenario();});
function loadScenario(){invalidate();const bundle=demoBundle($('scenario').value);for(const name of names)$('input-'+name).value=JSON.stringify(bundle[name],null,2);guide.hydrate(bundle);$('scenario-panel').hidden=false;$('class-label').textContent='DADOS FICTÍCIOS';$('mode-note').textContent='Demonstração explicitamente fictícia: dois medidores, preço constante, uso e estorno. Mude a situação ou edite as entradas; nada é enviado.';run();}
$('scenario').addEventListener('change',loadScenario);
$('use-own').addEventListener('click',()=>{reset();$('mode-note').textContent='Preencha contrato e fatura, cole ou abra o CSV normalizado dos eventos. Declare apenas fatos existentes e use IDs opacos. Dados desconhecidos continuam bloqueados. JSON normalizado continua disponível no modo avançado.';$('guided-data_class').focus();});
$('clear').addEventListener('click',reset);$('reconcile').addEventListener('click',()=>{if(guide.isActive()&&!guide.prepare())return;run();});
for(const name of names){$('input-'+name).addEventListener('input',()=>{guide.setMode('raw');invalidate();});$('file-'+name).addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;guide.setMode('raw');invalidate();const version=revision;if(file.size>2000000){showInputError(`${name}.json: arquivo excede 2 MB.`);return;}try{const raw=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(version!==revision)return;$('input-'+name).value=raw;$('mode-note').textContent='Arquivo carregado localmente. Abra os outros dois ou cole seu conteúdo, depois clique em Conferir agora.';}catch{showInputError(`${name}.json: não foi possível ler este arquivo como UTF-8 válido.`);}});}
$('download-json').addEventListener('click',()=>{if(current)download('usage-reconciliation.json',JSON.stringify(current.report,null,2)+'\n','application/json;charset=utf-8');});
$('download-csv').addEventListener('click',()=>{if(current&&current.report.status!=='blocked')download('usage-comparison.csv',csv(current.report),'text/csv;charset=utf-8');});
$('download-html').addEventListener('click',()=>{if(current)download('usage-reconciliation.html',reportHtml(current.report),'text/html;charset=utf-8');});

for(const id of ['trail-meter','trail-query'])$(id).addEventListener(id==='trail-query'?'input':'change',()=>{trailPage=0;if(current)renderTrail(current.report);});
$('trail-prev').addEventListener('click',()=>{trailPage--;if(current)renderTrail(current.report);});$('trail-next').addEventListener('click',()=>{trailPage++;if(current)renderTrail(current.report);});
$('download-dossier').addEventListener('click',()=>{if(!current)return;try{download('usage-dossier-v1.json',createDossier(current.raw,current.report),'application/json;charset=utf-8');}catch(e){showInputError(e.message);}});
$('file-dossier').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const version=revision,token=++dossierOperation;try{if(file.size>2000000)throw new Error('Dossiê limitado a 2 MB.');const raw=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(version!==revision||token!==dossierOperation)return;pendingDossier=parseDossier(raw);$('dossier-notice').textContent=`Dossiê lido; o conteúdo atual ainda não foi substituído. Estado arquivado: ${pendingDossier.archived_status}. ${pendingDossier.notice}`;$('dossier-confirmation').hidden=false;}catch(error){if(version!==revision||token!==dossierOperation)return;pendingDossier=null;$('dossier-confirmation').hidden=true;showInputError(error.message);}finally{e.target.value='';}});
$('confirm-dossier').addEventListener('click',()=>{if(!pendingDossier)return;const candidate=pendingDossier;pendingDossier=null;invalidate();guide.reset();guide.setMode('raw');for(const name of names)$('input-'+name).value=candidate.raw[name];$('dossier-confirmation').hidden=true;$('scenario-panel').hidden=true;$('mode-note').textContent='Dossiê retomado manualmente. complete:true, quando presente, é somente a declaração preservada do arquivo. O relatório anterior foi ignorado. Clique em Conferir agora para recalcular.';$('class-label').textContent='Dossiê retomado — ainda não conferido';});
$('cancel-dossier').addEventListener('click',()=>{pendingDossier=null;$('dossier-confirmation').hidden=true;});
