'use strict';
(function(){
 let workspace=null,generation=0,pending=false;
 const el=id=>document.getElementById(id),R=CatalogReview;
 const deliveryControls=document.createElement('div');deliveryControls.className='actions';
 const deliveryButtons=[];
 for(const [key,label]of [['spreadsheetCsv','Baixar CSV final para planilha'],['csv','Baixar CSV fiel — importar como texto'],['conflictsCsv','Baixar conflitos e lacunas CSV'],['provenanceJson','Baixar proveniência integral JSON']]){const button=document.createElement('button');button.type='button';button.className='light';button.textContent=label;button.disabled=true;button.addEventListener('click',()=>exportDelivery(key));deliveryControls.append(button);deliveryButtons.push(button);}
 const deliveryNotice=document.createElement('p');deliveryNotice.textContent='CSV final conserva todos os campos do lote e referencia a proveniência. A cópia para planilha acrescenta apóstrofo a células que possam virar fórmulas, com alterações registradas na proveniência; os originais não mudam. O CSV fiel pode conter fórmulas declaradas: importar tudo como texto. JSON preserva tipos e ausências. Nenhuma fonte foi reconsultada.';
 el('review-list').append(deliveryControls,deliveryNotice);
 // Keep controls beside the list when renderList replaces its children.
 function placeDelivery(){el('review-list').append(deliveryControls,deliveryNotice);}
 function core(){return {validate:validateRows,summarize:summarizeCatalog};}
 function controls(){for(const id of ['review-origin','review-target','review-status','review-reason','review-reference'])el(id).disabled=pending||!workspace;for(const id of ['review-save','review-package','review-report'])el(id).disabled=pending||!workspace;for(const button of deliveryButtons)button.disabled=pending||!workspace;el('review-remove').disabled=pending||!workspace?.decisions.some(d=>d.target_key===el('review-target').value);}
 function pick(){if(!workspace)return;const key=el('review-target').value,target=R.targets(workspace.rows,core().summarize).find(t=>t.key===key),d=workspace.decisions.find(d=>d.target_key===key);el('review-target-info').textContent=target?'IDs preservados: '+target.row_ids.join(', '):'';el('review-status').value=d?.status||'request_documentation';el('review-reason').value=d?.justification||'';el('review-reference').value=d?.declared_reference||'';controls();}
 function render(){el('review-target').replaceChildren();for(const t of R.targets(workspace.rows,core().summarize)){const o=document.createElement('option');o.value=t.key;o.textContent=t.label;el('review-target').append(o);}el('review-origin').value=workspace.origin;renderList();pick();}
 function renderList(){el('review-list').replaceChildren();const available=R.targets(workspace.rows,core().summarize);if(!workspace.decisions.length){const p=document.createElement('p');p.textContent='Nenhuma revisão registrada para este lote.';el('review-list').append(p);}for(const d of workspace.decisions){const p=document.createElement('p'),b=document.createElement('button');b.className='light';b.textContent='Editar '+available.find(t=>t.key===d.target_key).label;b.addEventListener('click',()=>{el('review-target').value=d.target_key;pick();});const span=document.createElement('span');span.textContent=' — '+R.statuses[d.status]+'. '+d.justification+' Referência declarada: '+d.declared_reference;p.append(b,span);el('review-list').append(p);}placeDelivery();}
 async function dataset(event){const token=++generation;pending=true;controls();try{const candidate=event.detail.workspace||await R.createWorkspace(event.detail.document||{rows:event.detail.rows},event.detail.origin,core().validate);if(token!==generation)return;workspace=candidate;render();el('review-status-message').textContent='Novo lote: revisões anteriores invalidadas. '+(workspace.original_document?'Envelope documental completo preservado no formato v2. ':'')+'Registre decisões sem alterar os originais.';}catch(e){if(token===generation)el('review-status-message').textContent=e.message;}finally{if(token===generation){pending=false;controls();}}}
 document.addEventListener('catalog:dataset',dataset);
 document.addEventListener('catalog:loading',()=>{generation++;pending=true;controls();});
 document.addEventListener('catalog:failed',()=>{pending=false;controls();});
 document.addEventListener('catalog:select-target',event=>{if(pending||!workspace)return;el('review-target').value=event.detail.key;pick();el('review-target').scrollIntoView({behavior:'smooth',block:'center'});});
 el('review-target').addEventListener('change',pick);
 function withOrigin(){const origin=el('review-origin').value;if(!origin.trim()||origin.length>500)throw Error('Origem declarada precisa ser texto não vazio até 500 caracteres.');return {...workspace,origin};}
 el('review-save').addEventListener('click',()=>{try{if(pending||!workspace)return;workspace=R.saveDecision(withOrigin(),{target_key:el('review-target').value,status:el('review-status').value,justification:el('review-reason').value,declared_reference:el('review-reference').value},core().summarize);renderList();controls();el('review-status-message').textContent='Revisão declarada registrada. Dados originais não foram alterados.';}catch(e){el('review-status-message').textContent='Revisão recusada: '+e.message;}});
 el('review-remove').addEventListener('click',()=>{if(pending||!workspace)return;workspace=R.removeDecision(workspace,el('review-target').value);renderList();pick();el('review-status-message').textContent='Revisão removida; registro original preservado.';});
 function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function exportDelivery(key){if(pending||!workspace)return;const token=generation,snapshot=workspace;try{const result=await R.exportCsvDelivery(withOrigin(),core().validate,core().summarize);if(token!==generation||snapshot!==workspace||pending)return;const names={csv:'catalog-final-raw.csv',spreadsheetCsv:'catalog-final-spreadsheet.csv',conflictsCsv:'catalog-conflicts-spreadsheet.csv',provenanceJson:'catalog-provenance.json'};download(result[key],names[key],key==='provenanceJson'?'application/json':'text/csv;charset=utf-8');el('review-status-message').textContent=result.rowCount+' linhas exportadas. '+result.neutralizationCount+' células neutralizadas nas cópias para planilha; consulte a proveniência. Originais intactos; não é aceite de cliente.';}catch(e){if(token===generation)el('review-status-message').textContent='Entrega recusada: '+e.message;}}
 el('review-package').addEventListener('click',()=>{try{if(pending||!workspace)return;download(R.exportPackage(withOrigin()),'catalog-review-workspace.json','application/json');}catch(e){el('review-status-message').textContent='Export recusado: '+e.message;}});
 el('review-report').addEventListener('click',()=>{try{if(pending||!workspace)return;download(R.reportHTML(withOrigin(),core().summarize),'catalog-review-report.html','text/html;charset=utf-8');}catch(e){el('review-status-message').textContent='Export recusado: '+e.message;}});
 el('review-file').addEventListener('change',async()=>{const token=++generation;document.dispatchEvent(new Event('catalog:cancel-load'));pending=true;controls();try{const file=el('review-file').files[0];if(!file)return;if(file.size>R.MAX_BYTES)throw Error('Pacote excede 4 MB.');const candidate=await R.importPackage(new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer()),core().validate,core().summarize);if(token!==generation)return;workspace=candidate;document.dispatchEvent(new CustomEvent('catalog:restore',{detail:{rows:structuredClone(workspace.rows),document:structuredClone(workspace.original_document||{rows:workspace.rows})}}));render();el('review-status-message').textContent='Pacote retomado: originais e revisões declaradas preservados. Hash não comprova fonte ou autoria.';}catch(e){if(token===generation)el('review-status-message').textContent='Importação recusada; dados e revisões anteriores preservados: '+e.message;}finally{if(token===generation){pending=false;controls();el('review-file').value='';}}});
})();
